// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/entry.proto

package raftpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Change struct {
	// id of the file that was changed
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// new hash of the file
	Hash uint64 `protobuf:"varint,2,opt,name=hash,proto3" json:"hash,omitempty"`
	// where the change starts (unused for now)
	Offset uint64 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	// size of the change
	Size                 uint64   `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Change) Reset()         { *m = Change{} }
func (m *Change) String() string { return proto.CompactTextString(m) }
func (*Change) ProtoMessage()    {}
func (*Change) Descriptor() ([]byte, []int) {
	return fileDescriptor_a245e8f22934927e, []int{0}
}

func (m *Change) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Change.Unmarshal(m, b)
}
func (m *Change) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Change.Marshal(b, m, deterministic)
}
func (m *Change) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Change.Merge(m, src)
}
func (m *Change) XXX_Size() int {
	return xxx_messageInfo_Change.Size(m)
}
func (m *Change) XXX_DiscardUnknown() {
	xxx_messageInfo_Change.DiscardUnknown(m)
}

var xxx_messageInfo_Change proto.InternalMessageInfo

func (m *Change) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Change) GetHash() uint64 {
	if m != nil {
		return m.Hash
	}
	return 0
}

func (m *Change) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *Change) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type Rename struct {
	// id of the renamed file
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// the id of the old parent of the file
	OldParentId uint64 `protobuf:"varint,2,opt,name=old_parent_id,json=oldParentId,proto3" json:"old_parent_id,omitempty"`
	// the id of the new parent of the file
	NewParentId uint64 `protobuf:"varint,3,opt,name=new_parent_id,json=newParentId,proto3" json:"new_parent_id,omitempty"`
	// the new name of the file
	NewName              string   `protobuf:"bytes,4,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rename) Reset()         { *m = Rename{} }
func (m *Rename) String() string { return proto.CompactTextString(m) }
func (*Rename) ProtoMessage()    {}
func (*Rename) Descriptor() ([]byte, []int) {
	return fileDescriptor_a245e8f22934927e, []int{1}
}

func (m *Rename) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rename.Unmarshal(m, b)
}
func (m *Rename) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rename.Marshal(b, m, deterministic)
}
func (m *Rename) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rename.Merge(m, src)
}
func (m *Rename) XXX_Size() int {
	return xxx_messageInfo_Rename.Size(m)
}
func (m *Rename) XXX_DiscardUnknown() {
	xxx_messageInfo_Rename.DiscardUnknown(m)
}

var xxx_messageInfo_Rename proto.InternalMessageInfo

func (m *Rename) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Rename) GetOldParentId() uint64 {
	if m != nil {
		return m.OldParentId
	}
	return 0
}

func (m *Rename) GetNewParentId() uint64 {
	if m != nil {
		return m.NewParentId
	}
	return 0
}

func (m *Rename) GetNewName() string {
	if m != nil {
		return m.NewName
	}
	return ""
}

type Delete struct {
	// id of the file to delete
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// id of the file's parent
	ParentId             uint64   `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Delete) Reset()         { *m = Delete{} }
func (m *Delete) String() string { return proto.CompactTextString(m) }
func (*Delete) ProtoMessage()    {}
func (*Delete) Descriptor() ([]byte, []int) {
	return fileDescriptor_a245e8f22934927e, []int{2}
}

func (m *Delete) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Delete.Unmarshal(m, b)
}
func (m *Delete) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Delete.Marshal(b, m, deterministic)
}
func (m *Delete) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Delete.Merge(m, src)
}
func (m *Delete) XXX_Size() int {
	return xxx_messageInfo_Delete.Size(m)
}
func (m *Delete) XXX_DiscardUnknown() {
	xxx_messageInfo_Delete.DiscardUnknown(m)
}

var xxx_messageInfo_Delete proto.InternalMessageInfo

func (m *Delete) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Delete) GetParentId() uint64 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

type Entry struct {
	// Types that are valid to be assigned to Message:
	//	*Entry_C
	//	*Entry_R
	//	*Entry_D
	Message              isEntry_Message `protobuf_oneof:"message"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}
func (*Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_a245e8f22934927e, []int{3}
}

func (m *Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entry.Unmarshal(m, b)
}
func (m *Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entry.Marshal(b, m, deterministic)
}
func (m *Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entry.Merge(m, src)
}
func (m *Entry) XXX_Size() int {
	return xxx_messageInfo_Entry.Size(m)
}
func (m *Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Entry proto.InternalMessageInfo

type isEntry_Message interface {
	isEntry_Message()
}

type Entry_C struct {
	C *Change `protobuf:"bytes,1,opt,name=c,proto3,oneof"`
}

type Entry_R struct {
	R *Rename `protobuf:"bytes,2,opt,name=r,proto3,oneof"`
}

type Entry_D struct {
	D *Delete `protobuf:"bytes,3,opt,name=d,proto3,oneof"`
}

func (*Entry_C) isEntry_Message() {}

func (*Entry_R) isEntry_Message() {}

func (*Entry_D) isEntry_Message() {}

func (m *Entry) GetMessage() isEntry_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *Entry) GetC() *Change {
	if x, ok := m.GetMessage().(*Entry_C); ok {
		return x.C
	}
	return nil
}

func (m *Entry) GetR() *Rename {
	if x, ok := m.GetMessage().(*Entry_R); ok {
		return x.R
	}
	return nil
}

func (m *Entry) GetD() *Delete {
	if x, ok := m.GetMessage().(*Entry_D); ok {
		return x.D
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Entry) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Entry_C)(nil),
		(*Entry_R)(nil),
		(*Entry_D)(nil),
	}
}

func init() {
	proto.RegisterType((*Change)(nil), "Change")
	proto.RegisterType((*Rename)(nil), "Rename")
	proto.RegisterType((*Delete)(nil), "Delete")
	proto.RegisterType((*Entry)(nil), "Entry")
}

func init() { proto.RegisterFile("pb/entry.proto", fileDescriptor_a245e8f22934927e) }

var fileDescriptor_a245e8f22934927e = []byte{
	// 264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x41, 0x4b, 0xf4, 0x30,
	0x10, 0x86, 0xbf, 0xf6, 0xab, 0x69, 0x3b, 0xc5, 0x3d, 0xf4, 0xa0, 0x15, 0x2f, 0xd2, 0x93, 0xa7,
	0x15, 0x14, 0xff, 0xc0, 0xaa, 0xa0, 0x17, 0x91, 0x9e, 0x44, 0x90, 0x25, 0xdd, 0x4c, 0xb7, 0x85,
	0x36, 0x09, 0x49, 0xa0, 0xa8, 0x7f, 0x5e, 0x26, 0x29, 0x22, 0xee, 0x6d, 0x3a, 0xef, 0x33, 0xf3,
	0x34, 0x03, 0x2b, 0xdd, 0x5e, 0xa1, 0x74, 0xe6, 0x63, 0xad, 0x8d, 0x72, 0xaa, 0x7e, 0x05, 0x76,
	0xd7, 0x73, 0xb9, 0xc7, 0x72, 0x05, 0xf1, 0x20, 0xaa, 0xe8, 0x22, 0xba, 0x4c, 0x9a, 0x78, 0x10,
	0x65, 0x09, 0x49, 0xcf, 0x6d, 0x5f, 0xc5, 0xbe, 0xe3, 0xeb, 0xf2, 0x04, 0x98, 0xea, 0x3a, 0x8b,
	0xae, 0xfa, 0xef, 0xbb, 0xcb, 0x17, 0xb1, 0x76, 0xf8, 0xc4, 0x2a, 0x09, 0x2c, 0xd5, 0xf5, 0x17,
	0xb0, 0x06, 0x25, 0x9f, 0x0e, 0x37, 0xd7, 0x70, 0xac, 0x46, 0xb1, 0xd5, 0xdc, 0xa0, 0x74, 0xdb,
	0x41, 0x2c, 0x8a, 0x42, 0x8d, 0xe2, 0xc5, 0xf7, 0x9e, 0x3c, 0x23, 0x71, 0xfe, 0xc5, 0x04, 0x61,
	0x21, 0x71, 0xfe, 0x61, 0xce, 0x20, 0x23, 0x86, 0x1c, 0xde, 0x9c, 0x37, 0xa9, 0xc4, 0xf9, 0x99,
	0x4f, 0x58, 0xdf, 0x02, 0xbb, 0xc7, 0x11, 0xdd, 0xa1, 0xfc, 0x1c, 0xf2, 0xbf, 0xe2, 0x4c, 0x2f,
	0x1b, 0xeb, 0x77, 0x38, 0x7a, 0xa0, 0xe3, 0x94, 0xa7, 0x10, 0xed, 0xfc, 0x50, 0x71, 0x9d, 0xae,
	0xc3, 0x81, 0x1e, 0xff, 0x35, 0xd1, 0x8e, 0x02, 0xe3, 0xc7, 0x28, 0x08, 0xef, 0xa3, 0xc0, 0x50,
	0x10, 0x7e, 0x92, 0x82, 0xe0, 0xa6, 0x40, 0x6c, 0x72, 0x48, 0x27, 0xb4, 0x96, 0xef, 0x71, 0x93,
	0xbd, 0x31, 0xc3, 0x3b, 0xa7, 0xdb, 0x96, 0xf9, 0xeb, 0xdf, 0x7c, 0x07, 0x00, 0x00, 0xff, 0xff,
	0xe0, 0x44, 0x22, 0x98, 0x8f, 0x01, 0x00, 0x00,
}
