// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/entry.proto

package raftpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Change struct {
	// id of the file that was changed
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// new hash of the file
	Hash uint64 `protobuf:"varint,2,opt,name=hash,proto3" json:"hash,omitempty"`
	// where the change starts (unused for now)
	Offset uint64 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	// size of the change
	Size                 uint64   `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Change) Reset()         { *m = Change{} }
func (m *Change) String() string { return proto.CompactTextString(m) }
func (*Change) ProtoMessage()    {}
func (*Change) Descriptor() ([]byte, []int) {
	return fileDescriptor_a245e8f22934927e, []int{0}
}

func (m *Change) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Change.Unmarshal(m, b)
}
func (m *Change) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Change.Marshal(b, m, deterministic)
}
func (m *Change) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Change.Merge(m, src)
}
func (m *Change) XXX_Size() int {
	return xxx_messageInfo_Change.Size(m)
}
func (m *Change) XXX_DiscardUnknown() {
	xxx_messageInfo_Change.DiscardUnknown(m)
}

var xxx_messageInfo_Change proto.InternalMessageInfo

func (m *Change) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Change) GetHash() uint64 {
	if m != nil {
		return m.Hash
	}
	return 0
}

func (m *Change) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *Change) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type Rename struct {
	// id of the renamed file
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// the id of the old parent of the file
	OldParentId uint64 `protobuf:"varint,2,opt,name=old_parent_id,json=oldParentId,proto3" json:"old_parent_id,omitempty"`
	// the id of the new parent of the file
	NewParentId uint64 `protobuf:"varint,3,opt,name=new_parent_id,json=newParentId,proto3" json:"new_parent_id,omitempty"`
	// the new name of the file
	NewName              string   `protobuf:"bytes,4,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rename) Reset()         { *m = Rename{} }
func (m *Rename) String() string { return proto.CompactTextString(m) }
func (*Rename) ProtoMessage()    {}
func (*Rename) Descriptor() ([]byte, []int) {
	return fileDescriptor_a245e8f22934927e, []int{1}
}

func (m *Rename) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rename.Unmarshal(m, b)
}
func (m *Rename) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rename.Marshal(b, m, deterministic)
}
func (m *Rename) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rename.Merge(m, src)
}
func (m *Rename) XXX_Size() int {
	return xxx_messageInfo_Rename.Size(m)
}
func (m *Rename) XXX_DiscardUnknown() {
	xxx_messageInfo_Rename.DiscardUnknown(m)
}

var xxx_messageInfo_Rename proto.InternalMessageInfo

func (m *Rename) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Rename) GetOldParentId() uint64 {
	if m != nil {
		return m.OldParentId
	}
	return 0
}

func (m *Rename) GetNewParentId() uint64 {
	if m != nil {
		return m.NewParentId
	}
	return 0
}

func (m *Rename) GetNewName() string {
	if m != nil {
		return m.NewName
	}
	return ""
}

type Delete struct {
	// id of the file to delete
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// id of the file's parent
	ParentId             uint64   `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Delete) Reset()         { *m = Delete{} }
func (m *Delete) String() string { return proto.CompactTextString(m) }
func (*Delete) ProtoMessage()    {}
func (*Delete) Descriptor() ([]byte, []int) {
	return fileDescriptor_a245e8f22934927e, []int{2}
}

func (m *Delete) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Delete.Unmarshal(m, b)
}
func (m *Delete) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Delete.Marshal(b, m, deterministic)
}
func (m *Delete) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Delete.Merge(m, src)
}
func (m *Delete) XXX_Size() int {
	return xxx_messageInfo_Delete.Size(m)
}
func (m *Delete) XXX_DiscardUnknown() {
	xxx_messageInfo_Delete.DiscardUnknown(m)
}

var xxx_messageInfo_Delete proto.InternalMessageInfo

func (m *Delete) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Delete) GetParentId() uint64 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func init() {
	proto.RegisterType((*Change)(nil), "Change")
	proto.RegisterType((*Rename)(nil), "Rename")
	proto.RegisterType((*Delete)(nil), "Delete")
}

func init() { proto.RegisterFile("pb/entry.proto", fileDescriptor_a245e8f22934927e) }

var fileDescriptor_a245e8f22934927e = []byte{
	// 214 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xb1, 0x4b, 0xc4, 0x30,
	0x14, 0xc6, 0x69, 0x2d, 0xb1, 0x7d, 0xc5, 0x0e, 0x19, 0x24, 0xe2, 0x22, 0x99, 0x9c, 0x74, 0x10,
	0xff, 0x01, 0x75, 0x71, 0x11, 0xe9, 0x24, 0x2e, 0x25, 0x25, 0xaf, 0xd7, 0x40, 0x9b, 0x84, 0x34,
	0x50, 0xee, 0xee, 0x9f, 0x3f, 0x92, 0x96, 0xe3, 0xb8, 0x6e, 0xdf, 0xfb, 0xf8, 0xf1, 0xfd, 0xe0,
	0x41, 0x65, 0xdb, 0x57, 0xd4, 0xde, 0xed, 0x5f, 0xac, 0x33, 0xde, 0xf0, 0x3f, 0x20, 0x9f, 0xbd,
	0xd0, 0x3b, 0xa4, 0x15, 0xa4, 0x4a, 0xb2, 0xe4, 0x29, 0x79, 0xce, 0xea, 0x54, 0x49, 0x4a, 0x21,
	0xeb, 0xc5, 0xd4, 0xb3, 0x34, 0x36, 0x31, 0xd3, 0x7b, 0x20, 0xa6, 0xeb, 0x26, 0xf4, 0xec, 0x26,
	0xb6, 0xeb, 0x15, 0xd8, 0x49, 0x1d, 0x90, 0x65, 0x0b, 0x1b, 0x32, 0x3f, 0x02, 0xa9, 0x51, 0x8b,
	0x71, 0xbb, 0xcc, 0xe1, 0xce, 0x0c, 0xb2, 0xb1, 0xc2, 0xa1, 0xf6, 0x8d, 0x92, 0xab, 0xa2, 0x34,
	0x83, 0xfc, 0x8d, 0xdd, 0x77, 0x64, 0x34, 0xce, 0x17, 0xcc, 0x22, 0x2c, 0x35, 0xce, 0x67, 0xe6,
	0x01, 0xf2, 0xc0, 0x04, 0x47, 0x34, 0x17, 0xf5, 0xad, 0xc6, 0xf9, 0x47, 0x8c, 0xc8, 0xdf, 0x81,
	0x7c, 0xe1, 0x80, 0x7e, 0x2b, 0x7f, 0x84, 0xe2, 0x5a, 0x9c, 0xdb, 0x75, 0xf1, 0x23, 0xff, 0x27,
	0x4e, 0x74, 0xde, 0xb6, 0x2d, 0x89, 0xef, 0x79, 0x3b, 0x05, 0x00, 0x00, 0xff, 0xff, 0x82, 0x4e,
	0xea, 0x1b, 0x30, 0x01, 0x00, 0x00,
}
