// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/entry.proto

package raftpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Change struct {
	// id of the file that was changed
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// new hash of the file
	Hash uint64 `protobuf:"varint,2,opt,name=hash,proto3" json:"hash,omitempty"`
	// where the change starts (unused for now)
	Offset uint64 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	// size of the change
	Size int64 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	// raft id of the peer who has the latest file
	PeerId               uint64   `protobuf:"varint,5,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Change) Reset()         { *m = Change{} }
func (m *Change) String() string { return proto.CompactTextString(m) }
func (*Change) ProtoMessage()    {}
func (*Change) Descriptor() ([]byte, []int) {
	return fileDescriptor_a245e8f22934927e, []int{0}
}

func (m *Change) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Change.Unmarshal(m, b)
}
func (m *Change) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Change.Marshal(b, m, deterministic)
}
func (m *Change) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Change.Merge(m, src)
}
func (m *Change) XXX_Size() int {
	return xxx_messageInfo_Change.Size(m)
}
func (m *Change) XXX_DiscardUnknown() {
	xxx_messageInfo_Change.DiscardUnknown(m)
}

var xxx_messageInfo_Change proto.InternalMessageInfo

func (m *Change) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Change) GetHash() uint64 {
	if m != nil {
		return m.Hash
	}
	return 0
}

func (m *Change) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *Change) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Change) GetPeerId() uint64 {
	if m != nil {
		return m.PeerId
	}
	return 0
}

type Rename struct {
	// id of the renamed file
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// the id of the old parent of the file
	OldParentId uint64 `protobuf:"varint,2,opt,name=old_parent_id,json=oldParentId,proto3" json:"old_parent_id,omitempty"`
	// the id of the new parent of the file
	NewParentId uint64 `protobuf:"varint,3,opt,name=new_parent_id,json=newParentId,proto3" json:"new_parent_id,omitempty"`
	// the new name of the file
	NewName              string   `protobuf:"bytes,4,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rename) Reset()         { *m = Rename{} }
func (m *Rename) String() string { return proto.CompactTextString(m) }
func (*Rename) ProtoMessage()    {}
func (*Rename) Descriptor() ([]byte, []int) {
	return fileDescriptor_a245e8f22934927e, []int{1}
}

func (m *Rename) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rename.Unmarshal(m, b)
}
func (m *Rename) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rename.Marshal(b, m, deterministic)
}
func (m *Rename) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rename.Merge(m, src)
}
func (m *Rename) XXX_Size() int {
	return xxx_messageInfo_Rename.Size(m)
}
func (m *Rename) XXX_DiscardUnknown() {
	xxx_messageInfo_Rename.DiscardUnknown(m)
}

var xxx_messageInfo_Rename proto.InternalMessageInfo

func (m *Rename) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Rename) GetOldParentId() uint64 {
	if m != nil {
		return m.OldParentId
	}
	return 0
}

func (m *Rename) GetNewParentId() uint64 {
	if m != nil {
		return m.NewParentId
	}
	return 0
}

func (m *Rename) GetNewName() string {
	if m != nil {
		return m.NewName
	}
	return ""
}

type Delete struct {
	// id of the file to delete
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// id of the file's parent
	ParentId             uint64   `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Delete) Reset()         { *m = Delete{} }
func (m *Delete) String() string { return proto.CompactTextString(m) }
func (*Delete) ProtoMessage()    {}
func (*Delete) Descriptor() ([]byte, []int) {
	return fileDescriptor_a245e8f22934927e, []int{2}
}

func (m *Delete) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Delete.Unmarshal(m, b)
}
func (m *Delete) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Delete.Marshal(b, m, deterministic)
}
func (m *Delete) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Delete.Merge(m, src)
}
func (m *Delete) XXX_Size() int {
	return xxx_messageInfo_Delete.Size(m)
}
func (m *Delete) XXX_DiscardUnknown() {
	xxx_messageInfo_Delete.DiscardUnknown(m)
}

var xxx_messageInfo_Delete proto.InternalMessageInfo

func (m *Delete) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Delete) GetParentId() uint64 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

type Add struct {
	// id of file to add
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// id of parent file
	ParentId uint64 `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	// file name
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// file mode (store.FileMode)
	Mode                 uint32   `protobuf:"varint,4,opt,name=mode,proto3" json:"mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Add) Reset()         { *m = Add{} }
func (m *Add) String() string { return proto.CompactTextString(m) }
func (*Add) ProtoMessage()    {}
func (*Add) Descriptor() ([]byte, []int) {
	return fileDescriptor_a245e8f22934927e, []int{3}
}

func (m *Add) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Add.Unmarshal(m, b)
}
func (m *Add) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Add.Marshal(b, m, deterministic)
}
func (m *Add) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Add.Merge(m, src)
}
func (m *Add) XXX_Size() int {
	return xxx_messageInfo_Add.Size(m)
}
func (m *Add) XXX_DiscardUnknown() {
	xxx_messageInfo_Add.DiscardUnknown(m)
}

var xxx_messageInfo_Add proto.InternalMessageInfo

func (m *Add) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Add) GetParentId() uint64 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func (m *Add) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Add) GetMode() uint32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

type Entry struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Message:
	//	*Entry_Rename
	//	*Entry_Delete
	//	*Entry_Change
	//	*Entry_Add
	Message              isEntry_Message `protobuf_oneof:"message"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}
func (*Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_a245e8f22934927e, []int{4}
}

func (m *Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entry.Unmarshal(m, b)
}
func (m *Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entry.Marshal(b, m, deterministic)
}
func (m *Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entry.Merge(m, src)
}
func (m *Entry) XXX_Size() int {
	return xxx_messageInfo_Entry.Size(m)
}
func (m *Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Entry proto.InternalMessageInfo

func (m *Entry) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type isEntry_Message interface {
	isEntry_Message()
}

type Entry_Rename struct {
	Rename *Rename `protobuf:"bytes,2,opt,name=rename,proto3,oneof"`
}

type Entry_Delete struct {
	Delete *Delete `protobuf:"bytes,3,opt,name=delete,proto3,oneof"`
}

type Entry_Change struct {
	Change *Change `protobuf:"bytes,4,opt,name=change,proto3,oneof"`
}

type Entry_Add struct {
	Add *Add `protobuf:"bytes,5,opt,name=add,proto3,oneof"`
}

func (*Entry_Rename) isEntry_Message() {}

func (*Entry_Delete) isEntry_Message() {}

func (*Entry_Change) isEntry_Message() {}

func (*Entry_Add) isEntry_Message() {}

func (m *Entry) GetMessage() isEntry_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *Entry) GetRename() *Rename {
	if x, ok := m.GetMessage().(*Entry_Rename); ok {
		return x.Rename
	}
	return nil
}

func (m *Entry) GetDelete() *Delete {
	if x, ok := m.GetMessage().(*Entry_Delete); ok {
		return x.Delete
	}
	return nil
}

func (m *Entry) GetChange() *Change {
	if x, ok := m.GetMessage().(*Entry_Change); ok {
		return x.Change
	}
	return nil
}

func (m *Entry) GetAdd() *Add {
	if x, ok := m.GetMessage().(*Entry_Add); ok {
		return x.Add
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Entry) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Entry_Rename)(nil),
		(*Entry_Delete)(nil),
		(*Entry_Change)(nil),
		(*Entry_Add)(nil),
	}
}

func init() {
	proto.RegisterType((*Change)(nil), "Change")
	proto.RegisterType((*Rename)(nil), "Rename")
	proto.RegisterType((*Delete)(nil), "Delete")
	proto.RegisterType((*Add)(nil), "Add")
	proto.RegisterType((*Entry)(nil), "Entry")
}

func init() { proto.RegisterFile("pb/entry.proto", fileDescriptor_a245e8f22934927e) }

var fileDescriptor_a245e8f22934927e = []byte{
	// 333 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xc1, 0x4e, 0xc2, 0x40,
	0x10, 0x86, 0x29, 0x2d, 0x5b, 0x98, 0x06, 0x0e, 0x3d, 0x68, 0x8d, 0x17, 0xec, 0x89, 0x13, 0x26,
	0x18, 0x1f, 0x00, 0xd4, 0x04, 0x2e, 0xc6, 0xec, 0x91, 0x0b, 0x59, 0x9c, 0x01, 0x9a, 0xd0, 0x6d,
	0x6d, 0x9b, 0x10, 0xf5, 0x79, 0x7c, 0x4f, 0x33, 0xb3, 0xc4, 0x18, 0x7b, 0xf2, 0x36, 0x3b, 0xf3,
	0xed, 0xfc, 0xff, 0xce, 0x2c, 0x8c, 0xca, 0xed, 0x2d, 0xd9, 0xa6, 0x7a, 0x9f, 0x96, 0x55, 0xd1,
	0x14, 0xe9, 0x1b, 0xa8, 0x87, 0x83, 0xb1, 0x7b, 0x8a, 0x47, 0xd0, 0xcd, 0x30, 0xf1, 0xc6, 0xde,
	0x24, 0xd0, 0xdd, 0x0c, 0xe3, 0x18, 0x82, 0x83, 0xa9, 0x0f, 0x49, 0x57, 0x32, 0x12, 0xc7, 0x17,
	0xa0, 0x8a, 0xdd, 0xae, 0xa6, 0x26, 0xf1, 0x25, 0x7b, 0x3e, 0x31, 0x5b, 0x67, 0x1f, 0x94, 0x04,
	0x63, 0x6f, 0xe2, 0x6b, 0x89, 0xe3, 0x4b, 0x08, 0x4b, 0xa2, 0x6a, 0x93, 0x61, 0xd2, 0x73, 0x30,
	0x1f, 0x57, 0x98, 0x7e, 0x82, 0xd2, 0x64, 0x4d, 0xde, 0x96, 0x4c, 0x61, 0x58, 0x1c, 0x71, 0x53,
	0x9a, 0x8a, 0x6c, 0xc3, 0x17, 0x9d, 0x76, 0x54, 0x1c, 0xf1, 0x45, 0x72, 0x2b, 0x61, 0x2c, 0x9d,
	0x7e, 0x31, 0xce, 0x49, 0x64, 0xe9, 0xf4, 0xc3, 0x5c, 0x41, 0x9f, 0x19, 0xd6, 0x10, 0x4b, 0x03,
	0x1d, 0x5a, 0x3a, 0x3d, 0x9b, 0x9c, 0xd2, 0x7b, 0x50, 0x8f, 0x74, 0xa4, 0xa6, 0x2d, 0x7e, 0x0d,
	0x83, 0xbf, 0xc2, 0xfd, 0xf2, 0xdc, 0x31, 0x5d, 0x83, 0x3f, 0x47, 0xfc, 0xd7, 0x1d, 0x1e, 0x8a,
	0x38, 0xf0, 0xc5, 0x81, 0xc4, 0x9c, 0xcb, 0x0b, 0x74, 0xae, 0x86, 0x5a, 0xe2, 0xf4, 0xcb, 0x83,
	0xde, 0x13, 0xaf, 0xa4, 0xd5, 0xfe, 0x06, 0x54, 0x25, 0x93, 0x92, 0xde, 0xd1, 0x2c, 0x9c, 0xba,
	0xc1, 0x2d, 0x3b, 0xfa, 0x5c, 0x60, 0x04, 0xe5, 0x3d, 0x22, 0xc3, 0x88, 0x7b, 0x1e, 0x23, 0xae,
	0xc0, 0xc8, 0xab, 0xac, 0x58, 0x54, 0x19, 0x71, 0x1b, 0x67, 0xc4, 0x15, 0xe2, 0x04, 0x7c, 0x83,
	0x6e, 0x4f, 0xd1, 0x2c, 0x98, 0xce, 0x11, 0x97, 0x1d, 0xcd, 0xa9, 0xc5, 0x00, 0xc2, 0x9c, 0xea,
	0xda, 0xec, 0x69, 0xd1, 0x5f, 0xab, 0xca, 0xec, 0x9a, 0x72, 0xbb, 0x55, 0xf2, 0x77, 0xee, 0xbe,
	0x03, 0x00, 0x00, 0xff, 0xff, 0xd2, 0xe7, 0xc5, 0xdc, 0x4d, 0x02, 0x00, 0x00,
}
