// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/snap.proto

package raftpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type File struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Hash                 uint64   `protobuf:"varint,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Mode                 uint32   `protobuf:"varint,4,opt,name=mode,proto3" json:"mode,omitempty"`
	Size                 int64    `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	Atime                int64    `protobuf:"varint,6,opt,name=atime,proto3" json:"atime,omitempty"`
	Mtime                int64    `protobuf:"varint,7,opt,name=mtime,proto3" json:"mtime,omitempty"`
	Children             []*File  `protobuf:"bytes,8,rep,name=children,proto3" json:"children,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3dc80b13e18bb94, []int{0}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *File) GetHash() uint64 {
	if m != nil {
		return m.Hash
	}
	return 0
}

func (m *File) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *File) GetMode() uint32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func (m *File) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *File) GetAtime() int64 {
	if m != nil {
		return m.Atime
	}
	return 0
}

func (m *File) GetMtime() int64 {
	if m != nil {
		return m.Mtime
	}
	return 0
}

func (m *File) GetChildren() []*File {
	if m != nil {
		return m.Children
	}
	return nil
}

type Peers struct {
	Peer                 []string `protobuf:"bytes,1,rep,name=peer,proto3" json:"peer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Peers) Reset()         { *m = Peers{} }
func (m *Peers) String() string { return proto.CompactTextString(m) }
func (*Peers) ProtoMessage()    {}
func (*Peers) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3dc80b13e18bb94, []int{1}
}

func (m *Peers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Peers.Unmarshal(m, b)
}
func (m *Peers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Peers.Marshal(b, m, deterministic)
}
func (m *Peers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Peers.Merge(m, src)
}
func (m *Peers) XXX_Size() int {
	return xxx_messageInfo_Peers.Size(m)
}
func (m *Peers) XXX_DiscardUnknown() {
	xxx_messageInfo_Peers.DiscardUnknown(m)
}

var xxx_messageInfo_Peers proto.InternalMessageInfo

func (m *Peers) GetPeer() []string {
	if m != nil {
		return m.Peer
	}
	return nil
}

type Snapshot struct {
	Root                 *File    `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	Peers                *Peers   `protobuf:"bytes,2,opt,name=peers,proto3" json:"peers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Snapshot) Reset()         { *m = Snapshot{} }
func (m *Snapshot) String() string { return proto.CompactTextString(m) }
func (*Snapshot) ProtoMessage()    {}
func (*Snapshot) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3dc80b13e18bb94, []int{2}
}

func (m *Snapshot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Snapshot.Unmarshal(m, b)
}
func (m *Snapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Snapshot.Marshal(b, m, deterministic)
}
func (m *Snapshot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Snapshot.Merge(m, src)
}
func (m *Snapshot) XXX_Size() int {
	return xxx_messageInfo_Snapshot.Size(m)
}
func (m *Snapshot) XXX_DiscardUnknown() {
	xxx_messageInfo_Snapshot.DiscardUnknown(m)
}

var xxx_messageInfo_Snapshot proto.InternalMessageInfo

func (m *Snapshot) GetRoot() *File {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *Snapshot) GetPeers() *Peers {
	if m != nil {
		return m.Peers
	}
	return nil
}

func init() {
	proto.RegisterType((*File)(nil), "File")
	proto.RegisterType((*Peers)(nil), "Peers")
	proto.RegisterType((*Snapshot)(nil), "Snapshot")
}

func init() { proto.RegisterFile("pb/snap.proto", fileDescriptor_e3dc80b13e18bb94) }

var fileDescriptor_e3dc80b13e18bb94 = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0xd0, 0xc1, 0x4e, 0xc4, 0x20,
	0x10, 0x06, 0xe0, 0xd0, 0x42, 0xad, 0xb3, 0x59, 0x0f, 0xc4, 0x03, 0x46, 0x0f, 0xd8, 0x13, 0xa7,
	0x9a, 0xac, 0x6f, 0xa0, 0x89, 0x67, 0x83, 0x37, 0x6f, 0xd4, 0x8e, 0x29, 0xc9, 0xb6, 0x10, 0xe0,
	0xe4, 0x7b, 0xf9, 0x7e, 0x1b, 0xa6, 0xc9, 0xde, 0xfe, 0xf9, 0x42, 0x86, 0x99, 0x81, 0x63, 0x9c,
	0x5e, 0xf2, 0xe6, 0xe2, 0x18, 0x53, 0x28, 0x61, 0xf8, 0x67, 0xc0, 0x3f, 0xfc, 0x19, 0xe5, 0x1d,
	0x34, 0x7e, 0x56, 0x4c, 0x33, 0xc3, 0x6d, 0xe3, 0x67, 0x29, 0x81, 0x2f, 0x2e, 0x2f, 0xaa, 0x21,
	0xa1, 0x5c, 0x6d, 0x73, 0x2b, 0xaa, 0x56, 0x33, 0x73, 0x6b, 0x29, 0x57, 0x5b, 0xc3, 0x8c, 0x8a,
	0x6b, 0x66, 0x8e, 0x96, 0x72, 0xb5, 0xec, 0xff, 0x50, 0x09, 0xcd, 0x4c, 0x6b, 0x29, 0xcb, 0x7b,
	0x10, 0xae, 0xf8, 0x15, 0x55, 0x47, 0xb8, 0x17, 0x55, 0x57, 0xd2, 0x9b, 0x5d, 0xa9, 0x90, 0xcf,
	0xd0, 0xff, 0x2c, 0xfe, 0x3c, 0x27, 0xdc, 0x54, 0xaf, 0x5b, 0x73, 0x38, 0x89, 0xb1, 0x0e, 0x69,
	0xaf, 0x3c, 0x3c, 0x82, 0xf8, 0x44, 0x4c, 0xb9, 0xfe, 0x15, 0x11, 0x93, 0x62, 0xba, 0xad, 0x33,
	0xd5, 0x3c, 0xbc, 0x43, 0xff, 0xb5, 0xb9, 0x98, 0x97, 0x50, 0xe4, 0x03, 0xf0, 0x14, 0x42, 0xa1,
	0xcd, 0xae, 0x7d, 0x88, 0xe4, 0x13, 0x88, 0xfa, 0x3c, 0xd3, 0x8e, 0x87, 0x53, 0x37, 0x52, 0x47,
	0xbb, 0xe3, 0x5b, 0xff, 0xdd, 0x25, 0xf7, 0x5b, 0xe2, 0x34, 0x75, 0x74, 0xaa, 0xd7, 0x4b, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x49, 0x34, 0xba, 0xe7, 0x3b, 0x01, 0x00, 0x00,
}
