// Code generated by protoc-gen-go. DO NOT EDIT.
// source: entry.proto

package raft

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Change struct {
	// id of the file that was changed
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// new hash of the file
	Hash uint64 `protobuf:"varint,2,opt,name=hash,proto3" json:"hash,omitempty"`
	// where the change starts (unused for now)
	Offset uint64 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	// size of the change
	Size                 uint64   `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Change) Reset()         { *m = Change{} }
func (m *Change) String() string { return proto.CompactTextString(m) }
func (*Change) ProtoMessage()    {}
func (*Change) Descriptor() ([]byte, []int) {
	return fileDescriptor_daa6c5b6c627940f, []int{0}
}

func (m *Change) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Change.Unmarshal(m, b)
}
func (m *Change) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Change.Marshal(b, m, deterministic)
}
func (m *Change) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Change.Merge(m, src)
}
func (m *Change) XXX_Size() int {
	return xxx_messageInfo_Change.Size(m)
}
func (m *Change) XXX_DiscardUnknown() {
	xxx_messageInfo_Change.DiscardUnknown(m)
}

var xxx_messageInfo_Change proto.InternalMessageInfo

func (m *Change) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Change) GetHash() uint64 {
	if m != nil {
		return m.Hash
	}
	return 0
}

func (m *Change) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *Change) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type Rename struct {
	// id of the renamed file
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// the id of the old parent of the file
	OldParentId uint64 `protobuf:"varint,2,opt,name=old_parent_id,json=oldParentId,proto3" json:"old_parent_id,omitempty"`
	// the id of the new parent of the file
	NewParentId uint64 `protobuf:"varint,3,opt,name=new_parent_id,json=newParentId,proto3" json:"new_parent_id,omitempty"`
	// the new name of the file
	NewName              string   `protobuf:"bytes,4,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rename) Reset()         { *m = Rename{} }
func (m *Rename) String() string { return proto.CompactTextString(m) }
func (*Rename) ProtoMessage()    {}
func (*Rename) Descriptor() ([]byte, []int) {
	return fileDescriptor_daa6c5b6c627940f, []int{1}
}

func (m *Rename) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rename.Unmarshal(m, b)
}
func (m *Rename) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rename.Marshal(b, m, deterministic)
}
func (m *Rename) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rename.Merge(m, src)
}
func (m *Rename) XXX_Size() int {
	return xxx_messageInfo_Rename.Size(m)
}
func (m *Rename) XXX_DiscardUnknown() {
	xxx_messageInfo_Rename.DiscardUnknown(m)
}

var xxx_messageInfo_Rename proto.InternalMessageInfo

func (m *Rename) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Rename) GetOldParentId() uint64 {
	if m != nil {
		return m.OldParentId
	}
	return 0
}

func (m *Rename) GetNewParentId() uint64 {
	if m != nil {
		return m.NewParentId
	}
	return 0
}

func (m *Rename) GetNewName() string {
	if m != nil {
		return m.NewName
	}
	return ""
}

type Delete struct {
	// id of the file to delete
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// id of the file's parent
	ParentId             uint64   `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Delete) Reset()         { *m = Delete{} }
func (m *Delete) String() string { return proto.CompactTextString(m) }
func (*Delete) ProtoMessage()    {}
func (*Delete) Descriptor() ([]byte, []int) {
	return fileDescriptor_daa6c5b6c627940f, []int{2}
}

func (m *Delete) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Delete.Unmarshal(m, b)
}
func (m *Delete) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Delete.Marshal(b, m, deterministic)
}
func (m *Delete) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Delete.Merge(m, src)
}
func (m *Delete) XXX_Size() int {
	return xxx_messageInfo_Delete.Size(m)
}
func (m *Delete) XXX_DiscardUnknown() {
	xxx_messageInfo_Delete.DiscardUnknown(m)
}

var xxx_messageInfo_Delete proto.InternalMessageInfo

func (m *Delete) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Delete) GetParentId() uint64 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

type RaftEntry struct {
	// Types that are valid to be assigned to Message:
	//	*RaftEntry_C
	//	*RaftEntry_R
	//	*RaftEntry_D
	Message              isRaftEntry_Message `protobuf_oneof:"message"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *RaftEntry) Reset()         { *m = RaftEntry{} }
func (m *RaftEntry) String() string { return proto.CompactTextString(m) }
func (*RaftEntry) ProtoMessage()    {}
func (*RaftEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_daa6c5b6c627940f, []int{3}
}

func (m *RaftEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RaftEntry.Unmarshal(m, b)
}
func (m *RaftEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RaftEntry.Marshal(b, m, deterministic)
}
func (m *RaftEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RaftEntry.Merge(m, src)
}
func (m *RaftEntry) XXX_Size() int {
	return xxx_messageInfo_RaftEntry.Size(m)
}
func (m *RaftEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_RaftEntry.DiscardUnknown(m)
}

var xxx_messageInfo_RaftEntry proto.InternalMessageInfo

type isRaftEntry_Message interface {
	isRaftEntry_Message()
}

type RaftEntry_C struct {
	C *Change `protobuf:"bytes,1,opt,name=c,proto3,oneof"`
}

type RaftEntry_R struct {
	R *Rename `protobuf:"bytes,2,opt,name=r,proto3,oneof"`
}

type RaftEntry_D struct {
	D *Delete `protobuf:"bytes,3,opt,name=d,proto3,oneof"`
}

func (*RaftEntry_C) isRaftEntry_Message() {}

func (*RaftEntry_R) isRaftEntry_Message() {}

func (*RaftEntry_D) isRaftEntry_Message() {}

func (m *RaftEntry) GetMessage() isRaftEntry_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *RaftEntry) GetC() *Change {
	if x, ok := m.GetMessage().(*RaftEntry_C); ok {
		return x.C
	}
	return nil
}

func (m *RaftEntry) GetR() *Rename {
	if x, ok := m.GetMessage().(*RaftEntry_R); ok {
		return x.R
	}
	return nil
}

func (m *RaftEntry) GetD() *Delete {
	if x, ok := m.GetMessage().(*RaftEntry_D); ok {
		return x.D
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*RaftEntry) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*RaftEntry_C)(nil),
		(*RaftEntry_R)(nil),
		(*RaftEntry_D)(nil),
	}
}

func init() {
	proto.RegisterType((*Change)(nil), "raft.Change")
	proto.RegisterType((*Rename)(nil), "raft.Rename")
	proto.RegisterType((*Delete)(nil), "raft.Delete")
	proto.RegisterType((*RaftEntry)(nil), "raft.RaftEntry")
}

func init() { proto.RegisterFile("entry.proto", fileDescriptor_daa6c5b6c627940f) }

var fileDescriptor_daa6c5b6c627940f = []byte{
	// 263 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0x4f, 0x4b, 0xc4, 0x30,
	0x10, 0xc5, 0xed, 0x5a, 0xb2, 0xdb, 0xa9, 0x7a, 0xc8, 0x41, 0x2a, 0x7a, 0x90, 0x9c, 0x3c, 0xf5,
	0xa0, 0xf8, 0x05, 0xfc, 0x03, 0x7a, 0x11, 0xc9, 0xc9, 0xdb, 0x12, 0x37, 0xd3, 0x6d, 0xa1, 0x4d,
	0x4a, 0x12, 0x28, 0xea, 0x97, 0x97, 0x49, 0x4a, 0x11, 0xf7, 0x36, 0x9d, 0xf7, 0x66, 0x7e, 0xd3,
	0x17, 0x28, 0xd1, 0x04, 0xf7, 0x55, 0x8f, 0xce, 0x06, 0xcb, 0x73, 0xa7, 0x9a, 0x20, 0x3e, 0x80,
	0x3d, 0xb6, 0xca, 0xec, 0x91, 0x9f, 0xc1, 0xaa, 0xd3, 0x55, 0x76, 0x9d, 0xdd, 0xe4, 0x72, 0xd5,
	0x69, 0xce, 0x21, 0x6f, 0x95, 0x6f, 0xab, 0x55, 0xec, 0xc4, 0x9a, 0x9f, 0x03, 0xb3, 0x4d, 0xe3,
	0x31, 0x54, 0xc7, 0xb1, 0x3b, 0x7f, 0x91, 0xd7, 0x77, 0xdf, 0x58, 0xe5, 0xc9, 0x4b, 0xb5, 0xf8,
	0x01, 0x26, 0xd1, 0xa8, 0xe1, 0x70, 0xb3, 0x80, 0x53, 0xdb, 0xeb, 0xed, 0xa8, 0x1c, 0x9a, 0xb0,
	0xed, 0xf4, 0x8c, 0x28, 0x6d, 0xaf, 0xdf, 0x63, 0xef, 0x35, 0x7a, 0x0c, 0x4e, 0x7f, 0x3c, 0x09,
	0x58, 0x1a, 0x9c, 0x16, 0xcf, 0x05, 0x6c, 0xc8, 0x43, 0x8c, 0x48, 0x2e, 0xe4, 0xda, 0xe0, 0xf4,
	0xa6, 0x06, 0x14, 0xf7, 0xc0, 0x9e, 0xb0, 0xc7, 0x70, 0x08, 0xbf, 0x84, 0xe2, 0x3f, 0x78, 0x33,
	0xce, 0x1b, 0xc5, 0x08, 0x85, 0x54, 0x4d, 0x78, 0xa6, 0x98, 0xf8, 0x15, 0x64, 0xbb, 0x38, 0x58,
	0xde, 0x9e, 0xd4, 0x14, 0x56, 0x9d, 0x92, 0x7a, 0x39, 0x92, 0xd9, 0x8e, 0x54, 0x17, 0xe7, 0x17,
	0x35, 0xfd, 0x2d, 0xa9, 0x8e, 0xd4, 0x74, 0xf2, 0xa2, 0xa6, 0x73, 0x48, 0xd5, 0x0f, 0x05, 0xac,
	0x07, 0xf4, 0x5e, 0xed, 0xf1, 0x93, 0xc5, 0xc7, 0xb8, 0xfb, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x27,
	0xb0, 0x00, 0x2d, 0x9b, 0x01, 0x00, 0x00,
}
